export const listOfObjects = [
  {
    id: "1",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "2",
    object_name: "Samir Apartman",
    owner: "Samir Šimić",
    type: "apartment",
    address: "Rova 23, Malinska",
  },
  {
    id: "3",
    object_name: "Villa jadran",
    owner: "Nika Nikić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "4",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "5",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "6",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "7",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "8",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "9",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "10",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "11",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
  {
    id: "12",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
  },
];

export const newReservations = [
  {
    id: "1",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "2",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "3",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "4",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "5",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "6",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "7",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "8",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
];
