export const listOfObjects = [
  {
    id: "1",
    object_name: "Villa božo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Villa božo",
    value: "1",
  },
  {
    id: "2",
    object_name: "Samir Apartman",
    owner: "Samir Šimić",
    type: "apartment",
    address: "Rova 23, Malinska",
    label: "Samir apartman",
    value: "2",
  },
  {
    id: "22",
    object_name: "Villa jadran",
    owner: "Nika Nikić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Villa jadran",
    value: "3",
  },
  {
    id: "4",
    object_name: "Villa pare",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Villa pare",
    value: "4",
  },
  {
    id: "5",
    object_name: "Villa lova",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Villa lova",
    value: "5",
  },
  {
    id: "6",
    object_name: "Villa andrea",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Villa andrea",
    value: "6",
  },
  {
    id: "7",
    object_name: "Apartman vigo",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Apartman vigo",
    value: "7",
  },
  {
    id: "8",
    object_name: "Villa rakija",
    owner: "Božo Božić",
    type: "villa",
    address: "Rova 23, Malinska",
    label: "Villa rakija",
    value: "8",
  },
];

export const newReservations = [
  {
    id: "1",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "2",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "3",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "4",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "5",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "6",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "7",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
  {
    id: "8",
    apartmanName: "Ime_apartmana",
    name: "Ime",
    arrivalDate: new Date(),
    endDate: new Date(),
    price: "200",
    howMuchPeople: 3,
    howManyNight: 7,
  },
];

export const modalDemoReservations = [];
